### ISSUE TITLE
CommonJS Wrapper

### ISSUE THREAD

**Issue by Plummat** [victorjonsson/jQuery-Form-Validator#189]
is there an easy way to wrap this for AMD, Common, Browserify, etc. ?

**Comment by swemaniac** [comment]
I use it with browserify but it requires a bit of a "hack" to be able to do require('jquery-form-validator'). Are you still wondering?

**Comment by gtb104** [comment]
@swemaniac I would be interested in knowing what hack needs to be done to use require('jquery-form-validator').

**Comment by swemaniac** [comment]
Sorry for the not-so-detailed answer, but I hope you can get something out of it (time, time!!).

This method simply requires the plugin file and exposes it as "jquery-form-validator" so that you can require() it. You need jQuery in the global scope though, for the plugin to find it. You can either include it in the html directly or use browserify-shim to point out the file. I haven't done that here. Then we need browserify-shim to tell browserify that the jquery dependency lives in the global scope.

package.json
```javascript
{
  "name": "my-package",
  "description": "my package",
  "private": true,
  "devDependencies": {
    "browserify": "^7.0.2",
    "browserify-shim": "^3.8.2",
    "gulp": "^3.8.10"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "jquery": "global:jQuery"
  }
}
```

gulpfile.js
```javascript
var b = browserify('./path/to/main.js');

b.external('jquery');
b.require('.path/to/jquery-form-validator.js', { expose: 'jquery-form-validator' });

b.bundle().pipe(...)
```

script file
```javascript
var $ = require('jquery');
require('jquery-form-validator');

$.validate(...)
```

If you're using bower you can do it like this to include the file automatically with "bower-resolve":

bower.json
```javascript
{
  "name": "my-package",
  "dependencies": {
    "jquery-form-validator": "~2.1.47"
  }
}
```

gulpfile.js
```javascript
var  bowerResolve = require('bower-resolve');
...
var b = browserify('./path/to/main.js');

b.external('jquery');

var bowerDeps = Object.keys(require('./path-to/bower.json').dependencies) || [];

bowerDeps.forEach(function(id) {
	b.require(bowerResolve.fastReadSync(id, { basedir: './path-to/bower_components' }), { expose: id });
});

b.bundle()......
```
