### ISSUE TITLE
More flexibility for server side validation

### ISSUE THREAD

**Issue by mbigatti** [victorjonsson/jQuery-Form-Validator#219]
Hi. I'm in a scenario where I'd like to use Spring JPA REST endpoints to do server side validation, to check if an element already exists in a repository (list of domain objects). 

To obtain that I forked requestServer and server side validator to add a single line of code in the server side response to populate the valid property of the JSON response.

It would be great if the server side validation implementation could accept a callback function to post filter the JSON response obtained from the server in order to be able to adapt to existing endpoints with different interface than required.

I see that jQuery has a $.ajaxPrefilter() method but none for post filter the response. It should be possibile to pass a dataFilter function to AJAX default configuration but that would affect all AJAX calls and not only the validation ones.

Related to this, I noticed that the error callback uses the alert() function. This also could be a point where to provide a custom function. In my project I'm not using the standard alert() function but a custom UI.

Thanks for listening.
M.

**Comment by victorjonsson** [comment]
okey, here's some random thoughts I get when reading this issue.

- Isn't it possible to inject some sort of middleware and alter the response sent out by the rest-server, so that it complies with the response required by jQuery-Form-Validator?

- Wouldn't it be more suitable to implement a new end-point in your API, dedicated to this task?

If your'e stubborn and absolutely want to fix this on the client side you could use the global dataFilter in combination with the event ajaxComplete. But it really feels like a h4ck, but then again must javascript code does :)

```js
var seemsToBeApiEndPointResponse = function(json) {
   // validate that this json-response can have been sent out from the API end-point
};
$(document).ajaxComplete(function(event,request, settings) {
  var apiEndPoint = ' ... ';
  if( settings.url == apiEndPoint ) {
    $.ajaxSettings.dataFilter = function(data, dataType) { 
      if( dataType == 'json' && seemsToBeApiEndPointResponse(data) ) {
          // alter data so that it complies with the response message required by jQuery-form-validator
         ...
         delete $.ajaxSettings.dataFilter; // remove this filter
      }
      return data;
    };
  } 
}); 
```

This could of course end up in errors if you have many ajax-requests being made simultaneously, that's why I added the function `seemsToBeApiEndPointResponse` that should return false if the message... like I said, very hackisch and implicit code but it probably works in 99% of the time.

**Comment by mbigatti** [comment]
Thank your for taking the time to respond. 

The only strategy I didn't investigate is the middleware injection, It could be possible that it is possible to do that. 

As I said in the issue, I'm not convinced in using dataFilter as a clean solution; also, implementing a new endpoint would require more work (in this project I'll have several validation like this one). 

For now I'll stuck with my local fork, as it fixes the problem for all validations with one line of code (sort of).

Thanks
M.

**Comment by victorjonsson** [comment]
No problems... I scratched the code example above. This would be more suitable (not risking errors due to the fact requests are made asynchronously)

```js
jQuery( document ).ajaxSend(function(evt, xhr, settings) {
  if( settings.url == apiEndPoint ) {
   settings.dataFilter = function(data, type) {
     // modify data so that i complies with the json-message required by jQuery-form-validator
     ...
     return data;
   }
  }
});
```

**Comment by victorjonsson** [comment]
By the way, the native alert message is only fired in case the ajax request fails due to a communications error with the server (the server sending out http status >= 400).
