### ISSUE TITLE
icon-fail is not showing, I mean please attach all images and css files please.

### ISSUE THREAD

**Issue by Riyazkhan1989** [victorjonsson/jQuery-Form-Validator#256]
icon-fail is not showing, I mean please attach all images and css files please.

**Comment by ReneMuetti** [comment]
What do you mean icons and CSS?
Approximately from the examples of the website?

If yes - which have nothing to do with the script. Therefore, these are not included. However, they are quite simple "get" to - Firefox helps because further (page information => Pictures) and the rest is easy on the CSS files to get.

It was probably not appended, so that each user can even define classes.

**Comment by victorjonsson** [comment]
This questions comes up now and again. I will therefor add a stylesheet to the plugin that gives you a default theme that includes icons.

**Comment by ReneMuetti** [comment]
hmm ... ok ....

**Comment by Riyazkhan1989** [comment]
Thanx sir.
