### ISSUE TITLE
Validators make field required

### ISSUE THREAD

**Issue by Billy-** [victorjonsson/jQuery-Form-Validator#340]
If I use the email validator, for instance; the form only validates if there is a valid email address in the field. However, if the field is not required, then it should also validate if the field is empty. This goes for all validators.

The fix could be as simple as updating each validator with a simple length check; https://github.com/Billy-/jQuery-Form-Validator/commit/e45ce0f69c0cda9ffa5cfafa4814eaa195618844

or do the check before all validators, and don't run them if the field is empty?

**Comment by victorjonsson** [comment]
I'm not sure I understand this. The following sentence is a contradiction: `However, if the field is not required, then it should also validate if the field is empty`.

If you have applied a validation rule to an input it must be given a value that follows this rule, otherwise the input will be flagged as invalid. This means that if you have `data-validation="email"` on an input all values not being a valid e-mail will be considered invalid, including an empty value. If you want the input to be optional (allowing an empty value) you add the attribute `data-validation-optional="true"`

However. If you're using the html5-module this concept will change, and all inputs will by default become optional (which is the ordinary behaviour in the browser). This means that you will have to state whether or not an input is required, regardless of what type of validation rule that is applied.

```html
<!-- Optional input -->
<input type="email" name="..." />

<!-- Mandatory input, only allowing valid e-mails -->
<input type="email" required name="..." />
```

**Comment by xonecas** [comment]
@victorjonsson this saved my ass, where else could I have learned about `data-validation-optional="true"` ? Did I miss it in the docs?

**Comment by victorjonsson** [comment]
http://www.formvalidator.net/#default-validators_optional

**Comment by simplicitytrade** [comment]
I got almost the same case:
Input-field: text
Activated validator: letternumeric
Additional attribute: data-validation-optional="true"

Everything´s fine if you step over the field (by TABbing through input fields). But if you type any non-letternumeric character, the field will be marked as invalid - OK so far. Now delete the non-letternumeric character and TAB out of the field --> the field will still be marked as invalid, the optional-markup is being ignored from this point.

Only way to achieve a valid field is to enter again a valid character, delete it again and step to next field. Now the field is valid and the form can be sumitted.

**Comment by victorjonsson** [comment]
This would be considered a bug...

**Comment by victorjonsson** [comment]
I have not been able to reproduce this. Must have been an unstable version of the plugin that was used.
