### ISSUE TITLE
data-sanitize-strip doesn't work

### ISSUE THREAD

**Issue by dubalizer** [victorjonsson/jQuery-Form-Validator#600]
When I run the following code below, I get this error in the Chrome Inspector Console and the page doesn't strip away anything.

sanitize.js:31 Uncaught TypeError: $.formUtils.registerLoadedModule is not a function
    at sanitize.js:31
    at sanitize.js:173

`<input 
	autocomplete="off" 
	data-sanitize="trim strip" 
	data-sanitize-strip="a" 
	data-validation="length" 
	data-validation-length="2-20" 
	name="name"
	placeholder=""
	type="text"
	value=”">`

`<script type="text/javascript" src="/templates/javascript/lib/jquery-form-validator/jquery.form-validator.min.js"></script>
<script>
	$j.validate({
		modules : 'security, toggleDisabled, sanitize'
	});
</script>`

**Comment by victorjonsson** [comment]
This should work:
http://jsbin.com/zebucisane/edit?html,js,output

The error you're getting means that you're using a newer version of the modules compared to the core library. This may be caused by browser cache. Looking at your markup it seems as you would be better of using cdnjs instead of hosting the js files yourself.

**Comment by alexeycrystal** [comment]
Yes, absolutely right! I also had this issue when taken the older version of the security.js module. Thanks for your answer.
